version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: redev_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    restart: always

  backend:
    build: ./backend
    container_name: redev_backend
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - mysql
      - redis
    command:
      [
        "bash",
        "-c",
        "./wait-for-it.sh mysql:${DATABASE_PORT} -- npm run migration:run && npm run seed && npm run
        start:prod",
      ]

    restart: always

  mysql:
    image: mysql:8.0
    container_name: redev_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redev_redis
    restart: always
    ports:
      - "6380:6379"

volumes:
  mysql_data:
